"""add column color for notes table

Revision ID: 7460abe20706
Revises: 049fad0c67c9
Create Date: 2024-11-21 20:49:03.565061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7460abe20706'
down_revision: Union[str, None] = '049fad0c67c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'color')
    # ### end Alembic commands ###
